name: "Build Doc"

on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]

jobs:
  doc:
    name: Build Doc
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with: 
        submodules: true
    - run: |
        git config --global user.name binggg
        git config --global user.email being99@qq.com
        npm i 
        npm run build:doc
        cd doc
        git add .
        git commit -am "doc(framework): update framework doc"
        git push
        cd ../
        git add .
        git commit -am "doc(readme): update readme doc"
        git push
