name: "Build Doc"

on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]

jobs:
  doc:
    name: Build Doc
    runs-on: ubuntu-latest

    
    
   
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
